[package]
name = "shell"
version = "0.1.0"
authors = ["martonlanga <martonlanga@gmail.com>"]
license = "MIT"
build = "build.rs"
edition = "2018"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "shell"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.4.2"

[dependencies]
neon = "0.4.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
subprocess = "0.2.4"
anyhow = "1.0.32"
regex = "1.3.9"
base64 = "0.12.3"
fuzzy-matcher = "*"
crossbeam-channel = "0.4.4"
crossbeam-utils = "0.7.2"
