[package]
name = "native"
version = "0.1.0"
authors = ["martonlanga <martonlanga@gmail.com>"]
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.32"
regex = "1.3.9"
base64 = "0.12.3"
fuzzy-matcher = "*"
crossbeam-channel = "0.4.4"
crossbeam-utils = "0.7.2"
napi = { git = "https://github.com/napi-rs/napi-rs" }
napi-derive = { git = "https://github.com/napi-rs/napi-rs" }

[build-dependencies]
napi-build = "0.2"
